# title: Hacker-Blog
title: Kavian-Blog

description: "I'm Kavian AmirMozafari MSc Student at the Sharif University of Technology studying computer security."
author:
  name: "Kavian AmirMozafari"
  email: "kavian.amirmozafari@student.sharif.edu"
  url: "https://kavianam.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Kavian AmirMozafari"
year : "2020"
